### ISSUE TITLE
Chaser scene shuffling

### ISSUE THREAD

**Issue by fxedel** [mcallegari/qlcplus#1002]
**Problem description**: I often create chasers that randomly turn some LEDs on/off. But I prefer having an unordered scene list over using the random mode as I want to control the exact play order (e.g. to avoid the same scene twice). Therefore, I manually resort the scenes so that they seem random.

**Desired solution**: A possibility to shuffle the scenes (give each scene a new random position)

**Possible implementation**: Add a shuffle button right below the "move updwards/downwards" buttons. Orient on the functionality of these buttons on how to swap scenes and then implement the Fisher-Yates shuffling algorithm.

I know this issue has a quite low importance, but as it also doesn't seem that difficult, it might be a good first code contribution for me.

**Comment by janosvitok** [comment]
The way random mode is implemented should satisfy your requirements.
Basically: The scenes are shuffled randomly, but each is run only once in a round. Once the round is finished, the scenes are shuffled again, taking care that the first from new round is not the same scene as last scene from the previous round.

Two rounds are remembered so that you can go back and forth in the same order even when you cross the round boundary (If you cross round boundary twice, the order will change).

Example:

Let's say chaser has 4 scenes A, B, C, D. For the first round, let's say they are shuffled to [B, D, A, C].
So the first scene to run is B, then D, A and C is the fourth one. When C is started, another round is prepared, taking care that C must not be the first to go. Let's say it's [D, C, A, B]. So 5th step is D, than again C, A, and 8th is B.

When you go back from e. g. 6th step (C), you get to 5th (D) then to 4th (C), etc. The order is kept.
However, when you reach 8th step, new order for 9..12 is computed and you can't go back below 5th step. If you do, new order for [1..4] is computed and [9..12] is forgotten.

Does this work for you?

**Comment by FloEdelmann** [comment]
Sometimes you want to order scenes so that e.g. the lights in one row do not light up from left to right, but in a seemingly "random" order -- but always the same.

This is cumbersome to achieve manually (shuffling by hand).

However, it could be useful to sort scenes in a chaser anyway (e.g. if new scenes are added at the end but named differently).

A possible solution would be to add a *sort* button that asks how the selected scenes should be sorted. Options would then be "By name (ascending)", "By name (descending)", "Randomly (shuffle)".

**Comment by fxedel** [comment]
Thanks @janosvitok for your answer.

Shuffling every round (the random mode) doesn't fit my requirements as I can't predict the order of the scenes.

Example:

The scenes A, B, C, D are for turning the respective LEDs A, B, C, D on. I want them to blink in an unordered arrangement that persists each round and can be adjusted manually, e.g.:
B C A D | B C A D | B C A D | ...

With random, the arrangement changes each round and I can't control it. It's possible that a scene will appear twice after each other or that the arrangement seems ordered:
C D B A | A B C D | D C A B

So I have to manually reorder the scenes in a way that they look unordered. With this, I can easily prevent the issues in the example with random. I can do this easily with 4 scenes, but what if we have 50? A shuffle button that shuffles the static order of the scenes once would make this manual procedure much more convenient.

**Comment by mcallegari** [comment]
I think we can close this now ?

**Comment by fxedel** [comment]
Sure. Thanks for the nice cooperation :+1:
