### ISSUE TITLE
fixture convertor from robe to qlc

### ISSUE THREAD

**Issue by vanous** [mcallegari/qlcplus#1028]
https://gist.github.com/vanous/3605a8a5e9b79e38ea5eab1d31204858

**Comment by mcallegari** [comment]
While I appreciate the effort, I'm not sure if it makes sense to include a Python conversion script.
In the engine, we've got a C++ parser for Avolites definitions (.d4)
The idea could be to add a parser for Robe fixtures as well, so that QLC+ can open the original version natively, without the need of converting the definition to qxf.

But that means writing C++ code, not Python.

**Comment by vanous** [comment]
Thanks for getting back. Feel free to do whatever with it :)

As for your d4 support, you are not parsing any of the channel functions, which is where all the heavy work usually happens.

You could use the script to convert the mentioned XMLs to QLC+ native libraries and add those to your repo, so people can use them. As for the mentioned ROBE XMLs, this will remain as they are but over time i am sure they will evolve into much more comprehensive ones, keep your eyes open (as per your library definition redesign).

cheers
