### ISSUE TITLE
v4 ShowManager hides scene functions when adding to a track

### ISSUE THREAD

**Issue by kpr0th** [mcallegari/qlcplus#1393]
**Describe the bug**
When adding a Scene function to a track in showmanager, a new sequence is created that is bound to the selected scene, and the scene ends up being marked as hidden and disappears the next time the showfile is opened.

**To Reproduce**
1. Create a scene function
2. Create a new show function and add the scene
3. Observe that a new sequence is created that's bound to the selected scene
4. Save and re-open the show file and observe that the scene is no longer visible.

**Expected behavior**
The scene should not get hidden.  Suggested fix: clone the scene before creating a new sequence to bind to it.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - QLC+ Version 4.12.7.xxx (built off of the git head as of last week)

**Comment by mcallegari** [comment]
This is not a bug. It's a wanted behavior of the Sequence logic.
If you read the forums you will find all the history that led to this decision.

**Comment by kpr0th** [comment]
I'm aware of the optimization that was done to hide scenes that only exist to support a sequence, i.e. that are created when a new sequence is created in the function manager.  But it was very unexpected to "lose" a scene that I added when messing around with the show manager.  Is there a feature that needs to use the actual scene I selected in this case, vs. a cloned copy of it?

**Comment by mcallegari** [comment]
A Scene bound to a Sequence becomes exclusive use of the Sequence itself.
In the past there were users reporting that a Scene used by a Sequence was changing channel values (which is exactly what a Sequence does to the bound Scene)
Therefore hiding the Scene was the drastic solution to avoid misunderstandings.

**Comment by kpr0th** [comment]
One more try - and please understand I'm not trying to be argumentative. I honestly think I've found a way to improve the program.  

I just went and read all the related forum posts I could find ([here](https://www.qlcplus.org/forum/viewtopic.php?f=21&t=12420&p=52674&hilit=sequence+show#p52674) and [here](https://www.qlcplus.org/forum/viewtopic.php?f=5&t=9495&p=42346&hilit=sequence+show#p42346) for example).

I believe I understand the goal of hiding the scene.  That's not what I'm questioning.

But rather - in the show manager's "+" button for adding existing functions: if I pick an existing scene to add, then that scene ends up hidden.  You and others have recommended copying an existing scene first, before adding it to a show.  My suggested improvement is simply to do that automatically for the user, so they don't have to.  Other than surprising people who are using to having to do this manually (hopefully a pleasant surprise), is there any particular downside to automatically cloning the selected scene before creating the sequence to tie to it?  

Note - I've already coded this up for my own use, and would be happy to share it back for consideration as a pull request.

**Comment by hjtappe** [comment]
@mcallegari , my 2ct. about this as a long-year user and a supporter of this project:

My situations are singular changing music and a few theather setting. For this, my workflow is:
- Start adding fixtures and grouping them to working light and alley lights as well as colow regions
- Defining Moving Head movements and stationary positions within these areas
- Defining Colors
- Defining RGB Color Macros in these groups
- Arranging it on the virtual console

At this state, I am able to control the show manually.

Only then, when I have setup the basics (including scenes and manual VC), I am starting automation in sequences.

This is now my user experience with the show manager:
When I was considering to use the show manager, my work was destroyed as the scenes I am using in the VC were no more accessible and I could no more access them. So I was reverting the showmanager work and manually creating timings in sequences instead.

So, from my user perspective, the behavior of the show manager is unexpected and disruptive, if not destructive to the existing work. In one of the forum threads, it is suggested to manually copy the scenes before putting them into the show manager.

As fas as I understand, this patch tries to automate that step and would help avoiding the surprise and confusion to solve the disruption in the user experience.

Take this as a user feedback, not as a directive, but from my perspective, copying the existing scenes and hiding the copy instead of the original sounds like a solution to greatly improve the user experience. Alternatively, separating timings from scenes or ignoring them and setting them in a show container which then carries the scene as a child might be another option to re-use the existing ones without interfering with other elements.

This could look like:
- Show Track
  - Show container element with show timing
    - Raw Scene with ignored default timing
- Sequence
  - Sequence entry container with sequence timing
    - Raw Scene with ignored default timing
- VC Control element
  - Raw Scene with using default timing
  - Timing element setting default times on scenes

That in fact would be my preference because it still allows to use and maintain one scene with channel levels and positions and use it in different time settings.
