### ISSUE TITLE
qlc+ velleman 

### ISSUE THREAD

**Issue by qb-core-dutch** [mcallegari/qlcplus#1406]
**Describe the bug**

**To Reproduce**
1. Go to '(https://www.qlcplus.org/docs/html_en_EN/vellemanoutput.html)'
2. Click on '[K8062D.dll file](https://www.qlcplus.org/misc/K8062DLL_mod1.zip)'
3. drop file in QLC+ main folder
4, open qlc+
5, add licht (i ise led par 56)
6 qlc+ close 

**Expected behavior**
add the lichts and can choose interface

 - OS: [Windows]
 - QLC+ Version [latest]

**Comment by mcallegari** [comment]
Sorry but I'm afraid it is time to drop the support for this device.
It was outdated and working badly 6 years ago when I wrote this article:
https://www.qlcplus.org/forum/viewtopic.php?t=9657

I can't image what's the status on Windows 10/11.
I just plugged my interface and it simply doesn't work because Windows 10 doesn't even install a required DLL anymore.
I can't really help here and I suggest to move to better and more supported devices.
