### ISSUE TITLE
Help: Input Profile Editor window on v5?

### ISSUE THREAD

**Issue by X-Raym** [mcallegari/qlcplus#1465]
Hi,

On v4 there is a window called Input Profile Editor, where we can say what MIDI CC channel to watch for a MIDI device for eg

![img](https://i.imgur.com/BnbsKzd.png)

I dont find this window on v5,

Am I missing something ?

Thx!

**Comment by mcallegari** [comment]
Please read the popup that is displayed **every time** you open v5.
Then click on the link that is written in that popup.
Finally, search "input profile editor"

Also, since you are a GitHub user (not sure if you're a developer or not) you should see from the latest commits that I'm implementing the input profile editor these days in v5. So this bug report is totally out of place.

**Comment by X-Raym** [comment]
@mcallegari My feedback was dumb and misplaced and your feedback makes me feel stupid at best. Please delete this github issue. This is useless doesnt require any history preservation. Sorry for having trying to contribute in some way.
