### ISSUE TITLE
16bit movement issues

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#1484]
Issue 1
https://www.qlcplus.org/forum/viewtopic.php?t=16788

Issue 2
https://www.qlcplus.org/forum/viewtopic.php?t=16789

Issue 3
https://www.qlcplus.org/forum/viewtopic.php?t=16790

**Comment by mcallegari** [comment]
16 bit fade is being worked on in the following branch
https://github.com/mcallegari/qlcplus/tree/16bitfade

**Comment by mcallegari** [comment]
Test version available for every platform
https://www.qlcplus.org/downloads/test/index.php?p=

**Comment by GGGss** [comment]
As a kind reminder - the HTP mechanism does not work correctly with 16bit values.
Say a scene has [MSB,LSB] 12,185 and another scene 13,22. Both scenes are active to trigger HTP. Doing the maths gives us 0x0C**B9** and 0x**0D**16. The engine will spit out 0x0DB9 as a result. It should be 0x0D16.

**Comment by mcallegari** [comment]
@GGGss I worked some more on 16bit. Can you please check the latest build from the 16bitfade branch?

![Screenshot_20240223_232530](https://github.com/mcallegari/qlcplus/assets/2951337/dfaa7cb3-039a-4f71-ae47-9d47a1d28a18)

**Comment by GGGss** [comment]
I can confirm the HTP logic in the engine is valid.
The LTP logic is - as expected - valid. Even in conflicting situations, the latest value wins.

**Comment by mcallegari** [comment]
Adding a case report
https://www.qlcplus.org/forum/viewtopic.php?t=17078

**Comment by mcallegari** [comment]
@GGGss another round of fixes. Apparently, relative EFX calculation has never worked as expected. Please check now.

**Comment by GGGss** [comment]
@mcallegari Checked and approved ... LSB values play nicely now ... 
I still need to test the outcome to the extremes (>255,255 <0,0 in what the EFX will produce. (I noticed you hard limited both limits into the code ... all well to me - because these are cases of operator-mind's errors!)

Let's use the sparse days to the public appearance of the v4.13 to debug a little more... - HTP & LTP couples now well-behave in my tests. A True 16b engine is born.

To me, this introduced a welcome add-on for the next version? True-relative-mode
https://www.qlcplus.org/forum/viewtopic.php?p=72057#p72057 - But please accept my gratitude for your efforts

**Comment by mcallegari** [comment]
@GGGss many thanks to you for testing!
I will now consider this task as closed.
