### ISSUE TITLE
OSC Channel Number Calculator off by one

### ISSUE THREAD

**Issue by qfulmina** [mcallegari/qlcplus#1585]
**Describe the bug**
The _OSC Channel Number Calculator_ at the _OSC Plugin configuration_ appears to be off by one.

**To Reproduce**
Go to **Input/Output**.
Choose **OSC Plugin**.
Input _/qlc/test_ to the **Channel Number Calculator**. You get _46808_ as the **Channel number**.
Create a Widget e.g. a Button in the Virtual Console.
Edit the properties and Auto detect External Input.
Send a test value to _/qlc/test_ and you get _46809_.
E.g. with this python script

```python
from pythonosc import udp_client

client = udp_client.SimpleUDPClient('127.0.0.1', 7700)

client.send_message("/qlc/test", 0.5)
```

This happens to all OSC paths.

**Expected behavior**
Same Channel Numbers.

**Screenshots**
![OSC Channel Number Calculator at the OSC Plugin configuration](https://github.com/mcallegari/qlcplus/assets/95013050/4af4f3b5-2e24-4d8f-891a-e71a2d0cf3bc)
![Detected Channel Number](https://github.com/mcallegari/qlcplus/assets/95013050/59262be6-b14b-4d52-a567-95b67f2be3b8)

**Desktop (please complete the following information):**
 - QLC+ Version 4.13.1

**Comment by mcallegari** [comment]
I think there is a misunderstanding here.
What you see in the input profile editor is channel + 1 but what is written in the profile is channel.
Check for example this
https://github.com/mcallegari/qlcplus/blob/master/resources/inputprofiles/TouchOSC-Automat5.qxi#L62
is presented as this

![Screenshot_20240616_211130](https://github.com/mcallegari/qlcplus/assets/2951337/b18a6c2e-82ac-4137-8b66-2f0f1f4a2755)

So the calculator si correct, since it outputs what you actually need to write in an input profile or your custom OSC node.
Closing.

**Comment by qfulmina** [comment]
Thanks for clarifying, @mcallegari 

> I think there is a misunderstanding here.

True. And sorry for that.

> What you see in the input profile editor is channel + 1 but what is written in the profile is channel. Check for example this https://github.com/mcallegari/qlcplus/blob/master/resources/inputprofiles/TouchOSC-Automat5.qxi#L62 is presented as this

Alright. Could we place a hint somewhere near the calculator? Tooltip, text, some kind of question mark icon, or the like?

I might not be the only one wondering that there is a difference and having a hard time remembering if and where to add 1 (or subtract?) when setting up the VC with channels calculated by the calculator.

**Comment by mcallegari** [comment]
Documentation updated
https://docs.qlcplus.org/v4/plugins/osc
