### ISSUE TITLE
[Feature Request] [Virtual Console] Button override mode

### ISSUE THREAD

**Issue by PROPHESSOR** [mcallegari/qlcplus#1643]
Assume there're two buttons and two fixtures. You click on "Both Red" button and both of them are filled in red. You click on "Left Blue" and the left fixture is filled in blue. You click on "Both Red" button again and both of them are filled in red again. So, when you click on some button with that mode, it overrides the values with the values of a scene assigned to it. There's no "On/Off" state.

It's very useful for live shows. For now you need to care about scene priorities, use a lot of solo frames, write scripts, and do other hacks to achieve the similar behavior.

P.S> For sure, "Flash" mode buttons should have higher priority while they are pressed.

**Comment by mcallegari** [comment]
What you described is called LTP...

**Comment by mcallegari** [comment]
Also, this has already been implemented on VC Buttons flash mode with version 4.13.0.
When you come directly to GitHub rather than writing in the forums (as already suggested) you are supposed to be either a developer or up-to-date with the latest development changes that you can test via GitHub actions.
You are also supposed to know the software and have read all the relevant documentation.

Please do not open any other ticket here. Use the forums. Thank you.
