### ISSUE TITLE
VC Cue List step fader not in sync on existing projects

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#614]
Reported in the forum.
Project attached here: http://www.qlcplus.org/forum/viewtopic.php?f=2&p=39729#p39718

Really weird.

**Comment by plugz** [comment]
3 fixes are possible:
https://github.com/plugz/qlcplus/commit/27349ae09efa55551b071fb359cd530027057875
- use qRound instead of qFloor in slotSlider1ValueChanged. I haven't tested this with a 255-sized cuelist but it should work.
- in slotCurrentStepChanged, block signals of m_slider1 before changing its value so we don't enter slotSlider1ValueChanged
- do both of those

**Comment by mcallegari** [comment]
@plugz thanks.
At the moment I'm into a storm of shit trying to figure out what got broken on the Raspberry Pi.
If you have time, please feel free to fix this issue.
It's very easy to reproduce with Santiago's project.

**Comment by plugz** [comment]
@mcallegari 
Yes, I have tested the fixes with Santiago's project, but want to test corner cases before pushing it. I'm short on time too.

**Comment by mcallegari** [comment]
Fixed by b031094263f9c4680fa56ea17d06b1b1894d1eee ?

**Comment by plugz** [comment]
Yes

**Comment by sbenejam** [comment]
I just compiled qlcplus 4.10.1 and the issue seems to be solved. I tested with the test workspace that I published in the forum and with an old workspace with a 28 steps cuelist changing the cuelist properties to use step fader. 
Good job!! ;-)
