### ISSUE TITLE
OSC plugin: add support for partial IP addresses

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#693]
The ArtNet plugin does it. Not sure about E1.31 cause many changes went in.

Basically the idea is to save only the variable part of an IP address to ensure the portability of a project.

For example, if my PC has IP 192.168.0.100 and I want to transmit to IP 192.168.0.35, only "35" has to be saved and if I load the same project on another PC (or a RPi) on a different IP class (e.g. 10.0.0.50), the project will still work and will transmit to 10.0.0.35.

It's more difficult to parse parameters this way, but it's worth it.
Right now the OSC plugin always save the entire IP address, which is not portable at all.

**Comment by plugz** [comment]
I have some questions about this.

First, the case you present:

> have a computer at address 192.168.0.100
> send data to 192.168.0.35
> load project on a raspi, IP address 10.0.0.50

I don't understand, why is the target IP address is supposed to be 10.0.0.35 ? This looks like a very specific case.



Then, what about these cases:

1. computer on subnet 192.168.x.x, sends data to 192.168.25.1. When loading workspace on raspi on subnet 10.0.0.x. Does the target IP address becomes 10.0.0.1 ? Where does the 25 go ?

2. I have a computer on subnet 192.168.0.x, IP address whatever, that sends data to the address 10.0.0.3, on another subnet. I load the workspace on a raspi on subnet 10.50.0.x, and still want the OSC packets to go to 10.0.0.3. If loading the workspaces replaces the target IP address to 10.50.0.3, this is not going to work.

**Comment by mcallegari** [comment]
For some reason I missed your post.
On a second thought, either way we're not going to cover all the cases.
To answer your questions:

> I don't understand, why is the target IP address is supposed to be 10.0.0.35 ? This looks like a very specific case.

When you transfer a project on the RPi, it might be on a different network. So you create a project on your PC like if it was sending receiving from a specific IP (that can or cannot exist), and then transfer on the Pi where the IP surely exists.

In any case one can make sure the IPs are the same on both devices, but it's not always possible.

> computer on subnet 192.168.x.x, sends data to 192.168.25.1. When loading workspace on raspi on subnet 10.0.0.x. Does the target IP address becomes 10.0.0.1 ? Where does the 25 go ?

The ArtNet plugin saves partial IPs up to the necessary nibble. In your example, 25.1 would be saved into the project and on a 10.* network it will result in 10.0.25.1. At least this is what I had in mind. If it doesn't work like that, then it's a bug.

This is where it is extracted (and saved later on): https://github.com/mcallegari/qlcplus/blob/master/plugins/artnet/src/configureartnet.cpp#L228
This is where it is restored:
https://github.com/mcallegari/qlcplus/blob/master/plugins/artnet/src/artnetcontroller.cpp#L170

> If loading the workspaces replaces the target IP address to 10.50.0.3, this is not going to work.

Correct. As I sadi, either way not all the cases are covered.

However, when supporting partial IPs, the project XML can be tweaked manually to force a full IP.
Saving the whole IP every time doesn't allow any manual intervention.

Anyway, just ideas. Lately I don't really have time to do anything on QLC+

**Comment by plugz** [comment]
> When you transfer a project on the RPi, it might be on a different network. So you create a project on your PC like if it was sending/receiving on a specific IP (that can or cannot exist), and then transfer on the Pi where the IP surely exists.

If the 192.168.0.35 target IP does not exist on the network my programming computer is on, but 10.0.0.35 exists on the other network, I'm not going to target 192.168.0.35. So I still don't understand the use case.


>> computer on subnet 192.168.x.x, sends data to 192.168.25.1. When loading workspace on raspi on subnet 10.0.0.x. Does the target IP address becomes 10.0.0.1 ? Where does the 25 go ?

> The ArtNet plugin saves partial IPs up to the necessary nibble. In your example, 25.1 would be saved into the project and on a 10.* network it will result in 10.0.25.1. At least this is what I had in mind. If it doesn't work like that, then it's a bug.

Yes, I just tested and it does work like you want to. I get the idea of what you did, but even though there is no bug, it's still failing in this case. The subnet of the raspi is 10.0.0.x. So the resulting IP address 10.0.25.1 makes no sense.

> This is where it is extracted (and saved later on): https://github.com/mcallegari/qlcplus/blob/master/plugins/artnet/src/configureartnet.cpp#L228
This is where it is restored:
https://github.com/mcallegari/qlcplus/blob/master/plugins/artnet/src/artnetcontroller.cpp#L170

Some issues here too:
- The last byte of an IP address can be 0 if netmask < 24. Currently it's not allowed. Wouldn't it be a good idea to use QHostAddress for handling error cases ?
- The IP is split into 4 bytes. What if my IP address is 192.168.10.129/25 ?




> > If loading the workspaces replaces the target IP address to 10.50.0.3, this is not going to work.

> Correct. As I said, either way not all the cases are covered.

What is not covered if we choose to not create mix-ups of IP addresses ?




I think in general trying to guess what part of the IP address the user wants to keep is not a good idea.

> Anyway, just ideas. Lately I don't really have time to do anything on QLC+

I ask all these questions because I want to take on the matters of parameters tuning for OSC/E1.31/ArtNet, I don't want to give you more work :) But I guess I tend to disagree with you on network matters :smile:

**Comment by mcallegari** [comment]
> If the 192.168.0.35 target IP does not exist on the network my programming computer is on, but 10.0.0.35 exists on the other network, I'm not going to target 192.168.0.35. So I still don't understand the use case.

Imagine this:
- you have a eDMX2 (http://dmxking.com/artnetsacn/edmx2-tx-rdm) with a static IP address which is 10.0.0.35
- you intend to use it live in a closed network with static IP addresses
- your RPi has IP 10.0.0.100
- you design your project on your PC which is on 192.168.0.x
- you target ArtNet to transmit on .35.
- save the project and load it to the RPi via web interface

The use case is consistent and the RPi will transmit ArtNet to 10.0.0.35, so the eDMX2 address, which is what you wanted

> The last byte of an IP address can be 0 if netmask < 24. Currently it's not allowed. Wouldn't it be a good idea to use QHostAddress for handling error cases ?

That could make sense as long as QHostAddress covers all the cases (including multicast). I wrote some low-tech code not to rely on Qt. Also keep in mind that Qt5 has some new helpers that Qt4 doesn't have

> I think in general trying to guess what part of the IP address the user wants to keep is not a good idea.

That's what I guess too.

> I ask all these questions because I want to take on the matters of parameters tuning for OSC/E1.31/ArtNet, I don't want to give you more work :) But I guess I tend to disagree with you on network matters :smile:

I don't mind disagreements as long as they are constructive, and I think they are :smile:

**Comment by plugz** [comment]
> I don't mind disagreements as long as they are constructive, and I think they are :smile: 

That's nice, because it's not over yet ! hehe

> Imagine this:
- you have a eDMX2 (http://dmxking.com/artnetsacn/edmx2-tx-rdm) with a static IP address which is 10.0.0.35
- you intend to use it live in a closed network with static IP addresses
- your RPi has IP 10.0.0.100
- you design your project on your PC which is on 192.168.0.x
- you target ArtNet to transmit on .35.
- save the project and load it to the RPi via web interface

> The use case is consistent and the RPi will transmit ArtNet to 10.0.0.35, so the eDMX2 address, which is what you wanted

So in this case, I know the final target IP address is 10.0.0.35.

I can put 10.0.0.35 in the target IP field. On the first network, there is nothing at 192.168.0.35, so there is no purpose in writing 192.168.0.35 in the IP field.


> > I think in general trying to guess what part of the IP address the user wants to keep is not a good idea.

> That's what I guess too.

Why do you want to do it then ? I'm confused :(

**Comment by mcallegari** [comment]
>>> I think in general trying to guess what part of the IP address the user wants to keep is not a good idea.
>> That's what I guess too.

> Why do you want to do it then ? I'm confused :(

It seemed like a good idea at first, but considering all the cases, maybe the full IP address can work
