### ISSUE TITLE
Linux/Qt5 - Opening a workspace from the "recent" list is not working

### ISSUE THREAD

**Issue by kripton** [mcallegari/qlcplus#823]
Following works with Qt4 (4.8.7) but not with Qt5 (5.5.1):
Open QLC+, click and hold the "Open" Icon until the list of recent workspaces appears. When a workspace-file is clicked, an error message appears telling me that the file cannot be found.
Opening the same file using the usual "Open File"-dialog or from the command line works without a problem.

**Comment by sbenejam** [comment]
I tested on Xubuntu 15.10 with Qt5(5.4.2) qlcplus_4.10.3 from GIT. No error
appeared opening file from recent workspaces.

2016-03-08 20:32 GMT+01:00 kripton <notifications@github.com>:

**Comment by kripton** [comment]
Thanks for testing! I'll have to debug it then ;)

**Comment by mcallegari** [comment]
The only case I know to have a wrong behaviour is:
- open a file from the command line with the -o option
- close and re-open QLC+
- click on recent list and select the last opened file

For some reason the workspace path is not absolute, so QLC+ is not able to open it anymore.

Is this the case of this ticket ?

Otherwise, please let's close this and re-open when we have something reproducible
Thanks

**Comment by kripton** [comment]
Will re-open when I debugged this

**Comment by EvansMike** [comment]
I can confirm this behaviour on Fedora 27 and QLC build from master, commit 0a43c18b1a362b4aea
