### ISSUE TITLE
VCXYPadFixture test unit failure

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#861]
This test unit fails on 32bit builds
https://github.com/mcallegari/qlcplus/blob/master/ui/test/vcxypadfixture/vcxypadfixture_test.cpp#L874

We really need to understand why and fix it

**Comment by janosvitok** [comment]
1. most probably it is related to te fact that I changed code and didn't change the test
2. most probably the test can be dropped since it just duplicates the runtime code (I need to think about this a bit)
3. I tried to run the tests in virtualbox VM running ubuntu 12.04 32-bit (host is ubuntu 16.04 x64).
I could not reproduce the failure (yet).

**Comment by janosvitok** [comment]
I could reproduce the issue. The problem is in rounding - when the range is reversed, it still rounds towards lower values, instead of higher, so the values are not symmetric (they are symmetric +/- 1)

**Comment by mcallegari** [comment]
for now addressed with b94811fead9f1b9f781aff80d7a4302d0e44cb33 but that's not a proper solution
