### ISSUE TITLE
Need a Hue Phillips plugin

### ISSUE THREAD

**Issue by gilbsfr24** [mcallegari/qlcplus#870]
Hello 
I have just started to try to write a new plugin for Phillips's hue blub.

https://github.com/gilbsfr24/qlcplus/tree/gilbsfr24-Hue-Patch/plugins/hue

But I have negative values in the function HUEController::sendDmx  in the QByteArray &dmxData 

I want to understand why?

I Had built (only) the plugin with the right version of QT. I see the plug on interfaces tab.
Now I am starting to  try with a rebuild of all the project, I will see

Have you allready meet this kind of problem?

**Comment by mcallegari** [comment]
So, you've opened an issue in the QLC+ project for a plugin that's not even upstream.
Have you read the GitHub template message where it says to start a forum thread instead of writing here ?

You could have had your answer which is: DMX data is unsigned, while QByteArray data is signed. So you need to cast to uchar.

I've had a quick look at your branch. Apart for wrong files you committed, I will not accept non-Apache 2.0 sources, so you need to find a way to exclude the libhue sources.

**Comment by gilbsfr24** [comment]
Sorry I will close this issue, and the next time I will write in the forum.
Thank you for the explantation of unsigned char. I can now go further with my branch.
The libHue is not needed but it was in my directory (and my project too) when I comited my source, I have to correct and re-commit.
Next step for this branch, is to add "discovery bridge", and the 2 channels mode.
Rds
