### ISSUE TITLE
Non-multipage frames with names are all blank

### ISSUE THREAD

**Issue by mcallegari** [mcallegari/qlcplus#955]
Open for tracking
http://www.qlcplus.org/forum/viewtopic.php?f=33&t=10910

**Comment by mcallegari** [comment]
Fixed by de85453448caa7ca5fbf2bb52305491db958b834

**Comment by siegmund42** [comment]
This is not yet fully fixed. If you try the second reproducing method from the thread above, the issue is still present:

> 1) Create a frame
2) Double-click it, give it the name "Caption", click OK
--> Frame name "Caption" displays properly now
3) Double-click the frame, turn on Multipage mode, click OK
--> Frame now has "Caption - Page Name" caption as expected
4) Double-click the frame, turn OFF Multipage mode, click OK
--> Frame keeps the (now incorrect) "Caption - Page Name" caption

**Comment by mcallegari** [comment]
Alright, confirmed. Gonna fix it.
