### ISSUE TITLE
Publish fixture validator source code

### ISSUE THREAD

**Issue by fxedel** [mcallegari/qlcplus#963]
Hello, we're developing the [Open Fixture Library](https://github.com/FloEdelmann/open-fixture-library) that stores fixtures in a json format and is able to export them to various existing fixture definition formats (currently qlcplus and ecue are supported).

We'd like to run automated tests on our generated qlcplus fixtures, but we don't want to spam your [online validator](http://www.qlcplus.org/fixture_validator.php) with lots of automated requests. Therefore, it would be very handy if you could publish the source code of the fixture validator as an executable script that we could use in our project with automated travis tests.

(see FloEdelmann/open-fixture-library#102)

**Comment by mcallegari** [comment]
Hi Flo. While I appreciate an effort to standardize the fixtures format, the question is: why ?

In an ideal world where every software/hardware decides to use your JSON format, you're basically inviting everyone to trash what they've done so far on their fixture format and write code and dedicate effort to support yours.

Moreover I don't think the adoption of JSON over the XML used by QLC+ can give much advantage in terms of software compatibility. XML can be parsed in a wide variety of languages with almost no effort, as well as JSON. (to be honest I haven't checked how Qt can parse JSON data, but I guess it would be trivial)

Furthermore, it seems your initiave is "open" while others are not. Every part of the QLC+ project is open and can be inspected online, so why not starting from an already open initiative and put efforts on it to improve it instead of reinventing the wheel ?
For example, we have a long standing aching issue in handling channels that change behaviour depending on other channel values. Maybe you can help us to find a solution for that ?

And again, you're grabbing fixtures from several projects, convert them...and then what ? Are we (QLC+ community) supposed to benefit other projects starting to use your JSON format and not take benefit the other way around unless we support JSON too ? Sounds pretty unfair to me.

Finally, to answer the request of this ticket: all the fixtures going upstream pass the online validator, so I don't see a point to validate them once more in your scripts. If you really want, I'll share the PHP code I've written but I don't see the point in it. (and no, I don't really have time to spend to convert PHP to your preferred scripting language)

Footnote: You don't know me and this probably looks harsh to you. But this is my way to say: let's start a discussion around the topic, before asking for things without the proper context.

**Comment by mcallegari** [comment]
And please spare us from introductions like this:

> To use lighting control software like QLC+ or e:cue, you need proprietary fixture definition files that describe your lighting hardware. Those can be difficult to create, find or convert from one format into another.

While that might apply to e:cue which is in german and it's not clear how to create a personality, QLC+ has its own fixture editor and doesn't really have a "proprietary" format. 
In my world, "proprietary" means something you have no clue how to create or edit, like the .docx format, which needs a reverse engineering process to become open.

**Comment by FloEdelmann** [comment]
Thanks for your quick and detailed responses @mcallegari and @janosvitok (via email)!

I guess I should start by explaining the roots of our project. My brother @fxedel and I were used to programming lighting shows with the [e:cue](http://ecue.de) software and – because at some point we found it being limited in functionality – wanted to try out other programs. I built a DMX interface with OLA and tried QLC+ and we kept on using that combination since then.

The problem we noticed during our testing phase was that all the fixture definitions we created for e:cue could not be easily converted for use with other software. The idea for a converter was born. Since we wanted our work to be as useful for other people as possible, we decided to make it a website that would store the fixtures in a wiki-like way (everybody can help improve it) and allow auto-generated fixture files in various formats (at the moment only for e:cue and QLC+) to be downloaded. An offline converter tool wouldn't be handy for most users and would prevent the collaboration on improving existing fixtures.

![screenshot-download](https://cloud.githubusercontent.com/assets/202916/25439451/c39520ea-2a9c-11e7-9947-753cd58de672.png)

We used a JSON format as the "storage container" and not `qxf` because there are some features in other programs that need entries in their fixture definitions which couldn't be represented in `qxf`. We wanted to include them all.

I did search for a standardized fixture format before starting but didn't find this [discussion](https://groups.google.com/forum/#!topic/open-lighting/vg4oZ6era8Q/discussion). As it seems though, there is no real progress since the last post there.

For converting, you also need an import function. We are currently working on finishing the online fixture editor. After that, we want to allow users to upload e.g. a QLC+ fixture file to pre-fill the fixture editor with its contents. Of course, we will have to deal with proper attribution of the copyright owners. The original author will be included in our format and we want to include a link to the original file (where possible).

So the incentive of our project is *by no means* to replace your (and others') fixture format with something different, but to give users a place where they can upload and download fixture files for multiple lighting programs and collaboratively help improving fixture quality.

That said, maybe our wording was an unfortunate choice. We didn't mean to call QLC+ or its fixtures "not open" when describing them as "proprietary", but simply say they are only useful with the QLC+ software. We will have to put a lot more effort into the descriptions, I think.

Also, we didn't really think about legal issues like GPL v3.0 and Apache v2.0 being incompatible. Although it rises the question: Can writing down a fixture's functions – in one format or another – be protected by a license? I'd love to hear your comments on that! We will also consider switching to Apache license if that helps.

Regarding the validation of the outputted fixture files: We didn't yet consider using your [schema](https://github.com/mcallegari/qlcplus/blob/master/resources/schemas/fixture.xsd). That will be a good start. I guess the validator does a bit more, though? It would be awesome to see the PHP source being open to make sure that all of our exported `qxf` files are valid and possibly could also be integrated into your library.

**Comment by mcallegari** [comment]
@FloEdelmann thanks for the explanation.
PHP validator attached.

Open source licenses are a very weird world. I have already had a quite long and not-so-productive discussion with people trying to integrate QLC+ in the Fedora repos.
Basically it ends up in being:
- Apache and GPL are not compatible, because of GPL
- the quibble is that when you deliver something in binary form (and I believe this includes packaging something like .deb or .rpm), it must have no license clash. So it's all black or white. In the QLC+ case it is Apache 2.0.

So I'm not sure if we can release the fixture definitions with a dual APL/GPL licensing. In any case if I understand correctly, the qxf files would stay in the QLC+ repo, while in your repo there will be only definitions in JSON format.
When doing an online conversion, instead, the user is explicitely doing an operation, so he can even break a licensing issue like switching from APL to GPL.

May I ask why the interchange format you adopted is JSON ? Is there something missing in our XML format that would be worth investing some time on ?

P.S. If you're interested, we've got a [D4 parser in C++](https://github.com/mcallegari/qlcplus/blob/master/engine/src/avolitesd4parser.cpp), for Avolites personalities, but I'm not sure about the legal implications.

[fixture_validator.php.zip](https://github.com/mcallegari/qlcplus/files/958899/fixture_validator.php.zip)

**Comment by FloEdelmann** [comment]
I'm glad to see you not being against our project :)

> In any case if I understand correctly, the qxf files would stay in the QLC+ repo, while in your repo there will be only definitions in JSON format.

Correct!

> Is there something missing in our XML format that would be worth investing some time on ?

If you like, have a look at our [schema](https://github.com/FloEdelmann/open-fixture-library/blob/master/fixtures/schema.js). Some differences I remember right now:

* channels can have `defaultValue`, `highlightValue`, `invert`, `constant`, `crossfade` and `precendence` attributes
* `channelType`s 'SingleColor' and 'MultiColor' are new
* fixtures can have more than one category
* fixtures have a default physical section, modes can override single physical properties
* fixtures can have `manualURL` and `comment` attributes
* multi-byte channel handling (`multiByteChannels`) is better, although I'm still not completely satisfied with that
* the import plugin will be stored to keep a reference to the original file

Our format is also likely to change as new plugins (e.g. DMXControl v3) bring new features like matrix definitions. Thus, we will possibly adapt the `heads` section to allow it to include position information (x/y).

Thanks for your clarification about the licensing. I guess we can keep it as it is for now. If there should be any further issues, be sure to let us know!

Also thank you very much for attaching the validator source. As it seems, most possible errors are already caught in our JSON tests. But it includes some test cases we could add there, too.

The D4 parser could be very useful as a plugin. We'll look into that for sure!

**Comment by FloEdelmann** [comment]
@mcallegari would you mind looking into [#106](https://github.com/FloEdelmann/open-fixture-library/pull/106) in our repo?

I changed the misleading parts, but maybe you have some more suggestions.

**Comment by mcallegari** [comment]
@FloEdelmann much better now, thanks.
I'll close this as it answers to the original request.

Question: when a user will convert a fixture from format X to QLC+ format, what is the licence to be applied to the converted file ? I need to know this to understand if I can accept a definition coming from your converter or not.

Last personal note: I've seen a few good ideas in your schema, and it is sad to get over with the fact that the QLC+ fixture definition was not adopted as base format for your converter project.
If it was 80% good, we could have join efforts to cover the remaining 20%. I would have been willing to move our fixtures into a new repo and add all the conversion scripts and tools. 
Instead you decided to start over and prevented any greater good to happen.
In any case, good luck with your project !

**Comment by fxedel** [comment]
@mcallegari actually, we didn't thought much about different licenses when we chose GPLv3. Now, after some research, we decided that the [MIT License might be a better solution](https://github.com/FloEdelmann/open-fixture-library/pull/109) for us as it is less restrictive but only demands to include a copy of copyright and license. Furthermore, it's compatible to Apache 2.0, so our generated fixtures can be used within QLC+ if you want to.

Of course it would have been nice to build on top of the existing `.qxf` format and we certainly don't rule out doing so in the future. However, it will be difficult to support a wide variety of different fixture formats whilst being bound to one specific format and always try to be downwards compatible.
